language: node_js

node_js:
  - "8.11.1"

install:
  - npm install -g firebase-tools
  - yarn install

script:
  - echo "========== Build Start =========="
  - yarn run build

branches:
  only:
    - master

cache: yarn

before_deploy: "echo 'ready?'"
deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT
  message: "Deploy!!"